# Generated by Django 3.2.7 on 2021-09-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_subjects_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
