# Generated by Django 3.2.7 on 2021-09-29 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_attendancereportstaff'),
        ('app', '0014_alter_attendancereport_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.staffs'),
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='user_type',
            field=models.TextField(default=1, max_length=30),
        ),
    ]
