# Generated by Django 3.2.7 on 2021-09-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='name',
            field=models.TextField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.TextField(max_length=150),
        ),
    ]
