# Generated by Django 3.2.7 on 2021-09-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_auto_20210927_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
