# Generated by Django 3.2.7 on 2021-09-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_alter_staffs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='role',
            field=models.TextField(default=1, max_length=200),
        ),
    ]
