# Generated by Django 3.2.7 on 2021-09-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0004_staffs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='role',
            field=models.TextField(max_length=200),
        ),
    ]
