# Generated by Django 3.2.7 on 2021-09-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0007_attendancereportstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='leave_status',
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='FeedBackStaffs',
        ),
    ]
